RESENTMENT---kernel
GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022 pull request #100
Opened 2022-10-15 07:34 UTC by PIYUSH-MISHRA-00

#93 
A kernel with a with a print message at the boot time.

2022-10-15 07:39 UTC, hiferli requested changes
You have another PR raised for this application.
Please remove this app from this PR since it would further create issues while merging the applications.

Thanks

2022-10-15 07:40 UTC, hiferli approved these changes
This project is fine.
Please just remove the App Dev project from this PR.

Thanks

2022-10-15 14:34 UTC, PIYUSH-MISHRA-00 commented
> This project is fine. Please just remove the App Dev project from this PR.
> 
> Thanks

Done

2022-10-19 03:19 UTC, KhushbooGupta2111 approved these changes

2022-10-19 03:28 UTC, merged