Safe-Editor
GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022 pull request #101
Opened 2022-10-15 07:39 UTC by PIYUSH-MISHRA-00

A Java based user authenticated text editor that stores the username and password in SHA-256 bit encryption form.

2022-10-15 07:41 UTC, hiferli requested changes
Please restrict this App Dev project to it's corresponding PR 
They would create issues while merging all of your PRs

Thanks

2022-10-15 07:42 UTC, hiferli approved these changes
This project is fine.
Just remove the App Dev project from this PR.

Thanks

2022-10-15 14:35 UTC, PIYUSH-MISHRA-00 commented
> This project is fine. Just remove the App Dev project from this PR.
> 
> Thanks

Done

2022-10-19 03:20 UTC, KhushbooGupta2111 approved these changes

2022-10-19 03:37 UTC, merged