Added python web scraper
GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022 pull request #72
Opened 2022-10-10 01:01 UTC by ij007

Added a python folder and a web scraper as the project.

2022-10-10 03:54 UTC, KhushbooGupta2111 requested changes
Please add a readme file talking including the installation guide, the features of this and what kind of contributions you would appreciate from others

2022-10-10 08:32 UTC, hiferli requested changes
The project is fine.
However, there are a few things that are to be taken care of and should be added in the README.
- Add the note that this project is made for Firefox web browser.
- The website scrapes the IMDb website 
- Exceptional handling in actor name 

And various other issues too.

2022-10-10 16:46 UTC, ij007 commented
Added the following:
- Readme.md file
- Requirements.txt
- Exception handling in code

2022-10-12 08:13 UTC, hiferli approved these changes

2022-10-12 08:14 UTC, merged