Git-Automation-Script
GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022 pull request #91
Opened 2022-10-14 07:11 UTC by PIYUSH-MISHRA-00

#89 
Git Automation BASH Script for git clone, pull and push for one time configuration and using git from the terminal using a menu driven approach.

2022-10-14 14:09 UTC, KhushbooGupta2111 requested changes
Please make the changes suggested by @hiferli .

2022-10-15 04:08 UTC, PIYUSH-MISHRA-00 commented
> Please make the changes suggested by @hiferli .

Done

2022-10-15 04:41 UTC, KhushbooGupta2111 approved these changes

2022-10-15 06:57 UTC, hiferli approved these changes

2022-10-15 06:58 UTC, hiferli approved these changes

2022-10-15 06:58 UTC, merged

2022-10-15 14:44 UTC, PIYUSH-MISHRA-00 commented
Please add hacktoberfest label if you can