ni_sh_a.char IDE for Python
GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022 pull request #92
Opened 2022-10-14 07:14 UTC by PIYUSH-MISHRA-00

#90 
A simple and basic interpreter to execute Python codes

2022-10-14 14:14 UTC, KhushbooGupta2111 requested changes
Shift it to the python projects folder

2022-10-15 04:09 UTC, PIYUSH-MISHRA-00 commented
> Shift it to the python projects folder

Shifted it to the python projects section.

2022-10-15 04:42 UTC, KhushbooGupta2111 approved these changes

2022-10-15 06:58 UTC, hiferli approved these changes

2022-10-15 18:43 UTC, merged